;this file for FamiTone5.1 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


ld49_title_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,266,221 ; New song

@instruments:
	.word @env6,@env0,@env0,@env1
	.word @env7,@env0,@env0,@env1
	.word @env1,@env9,@env0,@env0
	.word @env2,@env10,@env0,@env1
	.word @env3,@env0,@env0,@env12
	.word @env4,@env11,@env0,@env1
	.word @env5,@env0,@env0,@env13
	.word @env8,@env0,@env0,@env13

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cd,$ca,$c7,$c0,$05,$c0,$00,$05
@env2:
	.byte $cd,$c0,$00,$01
@env3:
	.byte $cf,$ce,$cd,$cd,$cc,$cc,$c5,$00,$06
@env4:
	.byte $c7,$cc,$cf,$c0,$02,$c0,$00,$05
@env5:
	.byte $c1,$03,$c2,$0b,$c3,$0b,$c2,$09,$c1,$1e,$c1,$00,$0a
@env6:
	.byte $cf,$02,$c0,$00,$02
@env7:
	.byte $cc,$c8,$c5,$c2,$c1,$00,$04
@env8:
	.byte $cf,$00,$00
@env9:
	.byte $cb,$cc,$cd,$ce,$00,$03
@env10:
	.byte $cc,$c9,$ca,$02,$cb,$02,$cc,$cc,$cd,$cd,$00,$09
@env11:
	.byte $cc,$ce,$cd,$00,$00
@env12:
	.byte $c2,$00,$00
@env13:
	.byte $c1,$00,$00


; New song
@song0ch0:
	.byte $fb,$03
@song0ch0loop:
@ref0:
	.byte $00,$bd
@ref1:
	.byte $bf
@ref2:
	.byte $bf
@ref3:
	.byte $bf
@ref4:
	.byte $7f,$60,$8c,$19,$85,$62,$87,$64,$87,$62,$a7
@ref5:
	.byte $72,$60,$82,$19,$71,$8e,$15,$73,$82,$20,$72,$8e,$15,$74,$60,$82
	.byte $25,$72,$62,$8e,$15,$75,$60,$82,$2c,$72,$62,$8e,$15,$76,$60,$82
	.byte $31,$72,$64,$8e,$15,$75,$60,$82,$2c,$71,$64,$8e,$15,$74,$60,$82
	.byte $25,$71,$62,$8e,$15,$73,$60,$82,$20,$71,$62,$8e,$15,$72,$60,$82
	.byte $19,$7c,$8c,$17,$83,$62,$87,$64,$87,$62,$87
@ref6:
	.byte $7f,$60,$19,$85,$62,$87,$64,$87,$62,$a7
	.byte $ff,$16
	.word @ref5
	.byte $fd
	.word @song0ch0loop

; New song
@song0ch1:
@song0ch1loop:
@ref8:
	.byte $88,$00,$81,$72,$88,$19,$81,$00,$85,$72,$25,$00,$83,$72,$19,$00
	.byte $72,$25,$81,$00,$9d
@ref9:
	.byte $bb,$72,$17,$00
@ref10:
	.byte $72,$18,$00,$72,$19,$81,$00,$85,$72,$25,$00,$83,$72,$19,$00,$72
	.byte $25,$81,$00,$9d
@ref11:
	.byte $bf
@ref12:
	.byte $7f,$60,$8c,$20,$85,$62,$87,$64,$87,$62,$a7
@ref13:
	.byte $71,$60,$8e,$1c,$81,$72,$83,$62,$87,$72,$64,$83,$71,$83,$62,$87
	.byte $71,$60,$1e,$81,$72,$83,$62,$87,$72,$64,$83,$71,$83,$62,$87
	.byte $ff,$05
	.word @ref12
	.byte $ff,$0e
	.word @ref13
	.byte $fd
	.word @song0ch1loop

; New song
@song0ch2:
@song0ch2loop:
@ref16:
	.byte $80,$25,$81,$00,$85,$31,$00,$83,$25,$00,$31,$81,$00,$a1
@ref17:
	.byte $b7,$23,$00,$24,$00
@ref18:
	.byte $25,$81,$00,$85,$31,$00,$83,$25,$00,$31,$81,$00,$81,$00,$9d
@ref19:
	.byte $bf
@ref20:
	.byte $25,$81,$00,$85,$31,$00,$83,$25,$00,$31,$81,$00,$a1
	.byte $ff,$05
	.word @ref17
	.byte $ff,$0f
	.word @ref18
@ref23:
	.byte $bf
	.byte $fd
	.word @song0ch2loop

; New song
@song0ch3:
@song0ch3loop:
@ref24:
	.byte $79,$86,$04,$85,$75,$8a,$04,$81,$75,$04,$81,$77,$84,$04,$85,$75
	.byte $8a,$04,$81,$75,$04,$81,$79,$86,$04,$85,$75,$8a,$04,$81,$75,$04
	.byte $81,$77,$84,$04,$85,$75,$8a,$04,$81,$75,$04,$81
@ref25:
	.byte $79,$86,$04,$85,$75,$8a,$04,$81,$75,$04,$81,$77,$84,$04,$85,$75
	.byte $8a,$04,$81,$77,$86,$04,$81,$79,$04,$85,$79,$04,$81,$75,$8a,$04
	.byte $81,$77,$84,$04,$85,$75,$8a,$04,$81,$75,$04,$81
	.byte $ff,$18
	.word @ref24
@ref27:
	.byte $79,$86,$04,$85,$75,$8a,$04,$81,$75,$04,$81,$77,$84,$04,$85,$75
	.byte $8a,$04,$81,$75,$04,$81,$79,$86,$04,$85,$79,$04,$81,$75,$8a,$04
	.byte $81,$77,$84,$04,$85,$75,$8a,$04,$81,$75,$04,$81
	.byte $ff,$18
	.word @ref24
	.byte $ff,$18
	.word @ref25
	.byte $ff,$18
	.word @ref24
	.byte $ff,$18
	.word @ref27
	.byte $fd
	.word @song0ch3loop

; New song
@song0ch4:
@song0ch4loop:
@ref32:
	.byte $bf
@ref33:
	.byte $bf
@ref34:
	.byte $bf
@ref35:
	.byte $bf
@ref36:
	.byte $81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81
	.byte $81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81
	.byte $ff,$20
	.word @ref36
	.byte $ff,$20
	.word @ref36
	.byte $ff,$20
	.word @ref36
	.byte $fd
	.word @song0ch4loop
